import type { ProjectSnapshot } from "./types";

export const demoSnapshot: ProjectSnapshot = {
  root: "/projects/atlas",
  name: "Atlas content review",
  active_plan: "PLAN-0012",
  loaded_at: Date.now(),
  plans: [
    {
      id: "PLAN-0011",
      title: "Establish the review foundation",
      status: "completed",
      created: "2026-07-18",
      updated: "2026-08-02",
      current_item: null,
      goal: "Establish the shared review vocabulary and evidence boundary.",
      non_goals: "No customer rollout.",
      source_path: "docs/plans/0011-review-foundation.md",
      work_items: [],
    },
    {
      id: "PLAN-0012",
      title: "Ship the first complete review workflow",
      status: "active",
      created: "2026-08-04",
      updated: "2026-09-07",
      current_item: "W-004",
      goal: "Editors can review a complete page, resolve findings, and retain source-bound evidence without leaving WordPress.",
      non_goals: "No theme-specific product fork and no automated publishing.",
      source_path: "docs/plans/0012-review-workflow.md",
      work_items: [
        {
          id: "W-001",
          title: "Normalize page sources",
          status: "done",
          depends_on: [],
          blocked_by: [],
          decisions: ["ADR-0018"],
          outcome: "The service presents one stable source model to every review adapter.",
          acceptance: "Fixture import preserves block order, metadata, and source references.",
          steps: [],
          evidence: ["18 source fixtures passed"],
          next_action: null,
        },
        {
          id: "W-002",
          title: "Store review sessions",
          status: "done",
          depends_on: ["W-001"],
          blocked_by: [],
          decisions: ["ADR-0021"],
          outcome: "A review survives navigation and can be resumed without losing evidence.",
          acceptance: "A saved review reloads with identical findings and evidence references.",
          steps: [],
          evidence: ["Persistence integration test passed"],
          next_action: null,
        },
        {
          id: "W-003",
          title: "Render grouped findings",
          status: "done",
          depends_on: ["W-002"],
          blocked_by: [],
          decisions: ["ADR-0024"],
          outcome: "Editors can scan findings by page region and consequence.",
          acceptance: "Populated desktop and narrow states preserve finding identity and action access.",
          steps: [],
          evidence: ["Rendered at 1440 px and 390 px"],
          next_action: null,
        },
        {
          id: "W-004",
          title: "Complete the editor resolution flow",
          status: "in_progress",
          depends_on: ["W-003"],
          blocked_by: [],
          decisions: ["ADR-0024", "ADR-0027"],
          outcome: "Editors can resolve, defer, or reopen a finding and always understand the saved state.",
          acceptance: "Keyboard and pointer flows preserve focus, state feedback, and recovery across all supported actions.",
          steps: ["Implement state transitions.", "Connect persistence.", "Inspect the rendered interaction."],
          evidence: [],
          next_action: "Connect the reopened state to the saved review session.",
        },
        {
          id: "W-005",
          title: "Run the pilot review",
          status: "todo",
          depends_on: ["W-004"],
          blocked_by: ["PILOT-CONTENT"],
          decisions: ["ADR-0027"],
          outcome: "The pilot produces a complete review record from representative content.",
          acceptance: "The evaluator completes the agreed page set and records observed limitations.",
          steps: [],
          evidence: [],
          next_action: "Obtain the representative pilot page set.",
        },
        {
          id: "W-006",
          title: "Prepare the bounded release",
          status: "todo",
          depends_on: ["W-005"],
          blocked_by: [],
          decisions: ["ADR-0027"],
          outcome: "A release candidate is available with claims limited to observed pilot evidence.",
          acceptance: "The package, release notes, and retained evidence agree on scope and limitations.",
          steps: [],
          evidence: [],
          next_action: "Wait for the completed pilot evidence.",
        },
      ],
    },
  ],
  decisions: [
    {
      id: "ADR-0018",
      title: "Keep the service core theme-independent",
      status: "accepted",
      created: "2026-07-18",
      accepted: "2026-07-18",
      scope: "architecture/core",
      supersedes: null,
      superseded_by: null,
      decision: "The review core consumes a theme-independent source model; theme integration remains an adapter.",
      problem: "Binding the core to one builder would make reuse and testing depend on that builder.",
      consequences: "Adapters must normalize their source before review, while the review pipeline stays reusable.",
      revisit_when: "A required source feature cannot be represented without losing material meaning.",
      source_path: "docs/decisions/0018-theme-independent-core.md",
    },
    {
      id: "ADR-0021",
      title: "Store review sessions in WordPress",
      status: "superseded",
      created: "2026-07-24",
      accepted: "2026-07-24",
      scope: "storage/reviews",
      supersedes: null,
      superseded_by: "ADR-0027",
      decision: "Store every review as one post-meta document.",
      problem: "Reviews need durable local storage.",
      consequences: "The first implementation was simple but made partial updates and audit queries expensive.",
      revisit_when: "Superseded by ADR-0027.",
      source_path: "docs/decisions/0021-store-review-post-meta.md",
    },
    {
      id: "ADR-0024",
      title: "Group findings by page region",
      status: "accepted",
      created: "2026-08-09",
      accepted: "2026-08-10",
      scope: "interface/findings",
      supersedes: null,
      superseded_by: null,
      decision: "Use page region as the primary finding group and consequence as supporting context.",
      problem: "A flat severity list separates findings from the content editors are inspecting.",
      consequences: "The interface follows the page structure while retaining consequence labels for prioritization.",
      revisit_when: "Observed reviews show that editors cannot locate high-consequence findings quickly enough.",
      source_path: "docs/decisions/0024-group-findings-by-region.md",
    },
    {
      id: "ADR-0027",
      title: "Use normalized review records",
      status: "accepted",
      created: "2026-08-27",
      accepted: "2026-08-30",
      scope: "storage/reviews",
      supersedes: "ADR-0021",
      superseded_by: null,
      decision: "Store sessions, findings, and evidence as related normalized records.",
      problem: "The post-meta document cannot support safe partial updates and useful audit queries.",
      consequences: "Persistence has more explicit relations and migration work, while state changes become bounded and queryable.",
      revisit_when: "Measured scale or portability costs outweigh the integrity and query benefits.",
      source_path: "docs/decisions/0027-normalized-review-records.md",
    },
    {
      id: "ADR-0030",
      title: "Automate low-risk resolution suggestions",
      status: "proposed",
      created: "2026-09-06",
      accepted: null,
      scope: "interface/resolution",
      supersedes: null,
      superseded_by: null,
      decision: "Offer source-bound suggestions for reversible wording findings while preserving explicit editor confirmation.",
      problem: "Repeated mechanical corrections consume review time.",
      consequences: "Editors gain a faster path, but the interface must preserve authorship and make unverified suggestions unmistakable.",
      revisit_when: "Pilot evidence shows low acceptance or frequent context loss.",
      source_path: "docs/decisions/0030-resolution-suggestions.md",
    },
  ],
};

export const paginationDemoSnapshot: ProjectSnapshot = {
  ...demoSnapshot,
  name: "Pagination demo",
  plans: demoSnapshot.plans.map((plan) => plan.id !== "PLAN-0012" ? plan : {
    ...plan,
    work_items: [
      ...plan.work_items,
      ...Array.from({ length: 199 }, (_, index) => ({
        id: `W-${String(index + 7).padStart(3, "0")}`,
        title: `Pagination fixture ${index + 7}`,
        status: "todo" as const,
        depends_on: [],
        blocked_by: [],
        decisions: [],
        outcome: "Keep enough representative Plan points available to verify pagination.",
        acceptance: "The item appears on its expected page.",
        steps: [],
        evidence: [],
        next_action: null,
      })),
    ],
  }),
  decisions: [
    ...demoSnapshot.decisions,
    ...Array.from({ length: 200 }, (_, index) => ({
      id: `ADR-${String(index + 31).padStart(4, "0")}`,
      title: `Pagination fixture ${index + 31}`,
      status: "accepted" as const,
      created: "2026-09-20",
      accepted: "2026-09-20",
      scope: "viewer/pagination",
      supersedes: null,
      superseded_by: null,
      decision: "Keep this representative Decision available to verify pagination.",
      problem: "Long Decision lists need reliable navigation.",
      consequences: "The fixture spans several pages without changing production data.",
      revisit_when: "The pagination test seam changes.",
      source_path: `docs/decisions/${String(index + 31).padStart(4, "0")}-pagination-fixture.md`,
    })),
  ],
};
